# Generated by Django 2.0.5 on 2019-03-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mid', models.CharField(max_length=50, verbose_name='绑定id')),
                ('img_name', models.CharField(max_length=50, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'db_table': 'image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mid', models.CharField(max_length=40, verbose_name='绑定id')),
                ('text', models.TextField(verbose_name='文本')),
            ],
            options={
                'verbose_name': '文本',
                'verbose_name_plural': '文本',
                'db_table': 'text',
                'managed': False,
            },
        ),
    ]
