# Generated by Django 2.0.5 on 2019-03-29 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatagoryF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标记名')),
            ],
            options={
                'verbose_name': '一类标记',
                'verbose_name_plural': '一类标记',
            },
        ),
        migrations.CreateModel(
            name='CatagoryS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标记名')),
                ('catagory_f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='label.CatagoryF', verbose_name='一级类别')),
            ],
            options={
                'verbose_name': '二级类别',
                'verbose_name_plural': '二级类别',
            },
        ),
        migrations.CreateModel(
            name='labelRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='标记时间')),
                ('catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='label.CatagoryS', verbose_name='类别')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Image', verbose_name='图片')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='标记人')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Text', verbose_name='文本')),
            ],
            options={
                'verbose_name': '标记记录',
                'verbose_name_plural': '标记记录',
            },
        ),
    ]
