# Generated by Django 2.0.5 on 2019-05-08 18:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='labelitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('mid', models.CharField(max_length=100, verbose_name='微博id')),
                ('text', models.TextField(verbose_name='文本')),
                ('time', models.TimeField(default=datetime.datetime.now, verbose_name='标记时间')),
                ('cat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='label.CatagoryS', verbose_name='类别')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='标记人')),
            ],
            options={
                'verbose_name': '标记记录',
                'verbose_name_plural': '标记记录',
            },
        ),
        migrations.AlterModelOptions(
            name='labelrecord',
            options={},
        ),
        migrations.RemoveField(
            model_name='labelrecord',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='labelrecord',
            name='time',
        ),
    ]
