# Generated by Django 2.0.5 on 2019-05-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20190508_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelrecord',
            name='has_done',
            field=models.BooleanField(default=False),
        ),
    ]
