# Generated by Django 2.0.5 on 2019-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0004_labelitem_objects_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagorys',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='说明'),
        ),
    ]
